package com.yundroid.kokpit.commands;

public enum Animation {
	ARDRONE_ANIM_PHI_M30_DEG(1000),
	ARDRONE_ANIM_PHI_30_DEG(1000),		
	ARDRONE_ANIM_THETA_M30_DEG(1000),
	ARDRONE_ANIM_THETA_30_DEG(1000),
	ARDRONE_ANIM_THETA_20DEG_YAW_200DEG(1000),
	ARDRONE_ANIM_THETA_20DEG_YAW_M200DEG(1000),
	ARDRONE_ANIM_TURNAROUND(5000),
	ARDRONE_ANIM_TURNAROUND_GODOWN(5000),
	ARDRONE_ANIM_YAW_SHAKE(2000),
	ARDRONE_ANIM_YAW_DANCE(5000),
	ARDRONE_ANIM_PHI_DANCE(5000),
	ARDRONE_ANIM_THETA_DANCE(5000),
	ARDRONE_ANIM_VZ_DANCE(5000),
	ARDRONE_ANIM_WAVE(5000),
	ARDRONE_ANIM_PHI_THETA_MIXED(5000),			
	ARDRONE_ANIM_DOUBLE_PHI_THETA_MIXED(5000),
	ARDRONE_ANIM_FLIP_AHEAD(15),
	ARDRONE_ANIM_FLIP_BEHIND(15),
	ARDRONE_ANIM_FLIP_LEFT(15),
	ARDRONE_ANIM_FLIP_RIGHT(15);
	
	private int defaultDuration;
	
	private Animation(int defaultDuration){
		this.defaultDuration = defaultDuration;
	}
	
	public int getDefaultDuration(){
		return defaultDuration;
	}
}
